Write-Host "Nimblco bootstrap"
Write-Host ""
Write-Host "Next recommended steps:"
Write-Host "1. Add your application code under apps/ or packages/."
Write-Host "2. Run pnpm install after you add package manifests, or use npm.cmd exec --yes -- pnpm install if pnpm is not installed globally."
Write-Host "3. Fill in docs/ai/project-context.md with real product details."
Write-Host "4. Update docs/ai/architecture.md as the repo structure becomes real."
Write-Host "5. Update docs/ai/commands.md with real build, test, and lint commands."
Write-Host "6. Run ./scripts/check.ps1 after you add project tooling."
